/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Tag
    /// </summary>
    [DataContract(Name = "Tag")]
    public partial class Tag : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Tag for value: Tag
            /// </summary>
            [EnumMember(Value = "Tag")]
            Tag = 1
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "@type", EmitDefaultValue = false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Tag" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="type">type.</param>
        /// <param name="name">name.</param>
        /// <param name="owningProject">owningProject.</param>
        /// <param name="referencedCommit">referencedCommit.</param>
        /// <param name="taggedCommit">taggedCommit.</param>
        /// <param name="timestamp">timestamp.</param>
        public Tag(Guid id = default(Guid), TypeEnum? type = default(TypeEnum?), string name = default(string), BranchOwningProject owningProject = default(BranchOwningProject), BranchHead referencedCommit = default(BranchHead), BranchHead taggedCommit = default(BranchHead), DateTime timestamp = default(DateTime))
        {
            this.Id = id;
            this.Type = type;
            this.Name = name;
            this.OwningProject = owningProject;
            this.ReferencedCommit = referencedCommit;
            this.TaggedCommit = taggedCommit;
            this.Timestamp = timestamp;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "@id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets OwningProject
        /// </summary>
        [DataMember(Name = "owningProject", EmitDefaultValue = false)]
        public BranchOwningProject OwningProject { get; set; }

        /// <summary>
        /// Gets or Sets ReferencedCommit
        /// </summary>
        [DataMember(Name = "referencedCommit", EmitDefaultValue = false)]
        public BranchHead ReferencedCommit { get; set; }

        /// <summary>
        /// Gets or Sets TaggedCommit
        /// </summary>
        [DataMember(Name = "taggedCommit", EmitDefaultValue = false)]
        public BranchHead TaggedCommit { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name = "timestamp", EmitDefaultValue = false)]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Tag {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OwningProject: ").Append(OwningProject).Append("\n");
            sb.Append("  ReferencedCommit: ").Append(ReferencedCommit).Append("\n");
            sb.Append("  TaggedCommit: ").Append(TaggedCommit).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
