/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing CommitApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CommitApiTests : IDisposable
    {
        private CommitApi instance;

        public CommitApiTests()
        {
            instance = new CommitApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommitApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CommitApi
            //Assert.IsType<CommitApi>(instance);
        }

        /// <summary>
        /// Test GetCommitByProjectAndId
        /// </summary>
        [Fact]
        public void GetCommitByProjectAndIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid projectId = null;
            //Guid commitId = null;
            //var response = instance.GetCommitByProjectAndId(projectId, commitId);
            //Assert.IsType<Commit>(response);
        }

        /// <summary>
        /// Test GetCommitsByProject
        /// </summary>
        [Fact]
        public void GetCommitsByProjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid projectId = null;
            //string pageAfter = null;
            //string pageBefore = null;
            //int? pageSize = null;
            //var response = instance.GetCommitsByProject(projectId, pageAfter, pageBefore, pageSize);
            //Assert.IsType<List<Commit>>(response);
        }

        /// <summary>
        /// Test PostCommitByProject
        /// </summary>
        [Fact]
        public void PostCommitByProjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid projectId = null;
            //Commit body = null;
            //Guid? branchId = null;
            //var response = instance.PostCommitByProject(projectId, body, branchId);
            //Assert.IsType<Commit>(response);
        }
    }
}
