/*
 * SysML v2 API and Services
 *
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ProjectApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProjectApiTests : IDisposable
    {
        private ProjectApi instance;

        public ProjectApiTests()
        {
            instance = new ProjectApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProjectApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProjectApi
            //Assert.IsType<ProjectApi>(instance);
        }

        /// <summary>
        /// Test DeleteProjectById
        /// </summary>
        [Fact]
        public void DeleteProjectByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid projectId = null;
            //var response = instance.DeleteProjectById(projectId);
            //Assert.IsType<Project>(response);
        }

        /// <summary>
        /// Test GetProjectById
        /// </summary>
        [Fact]
        public void GetProjectByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid projectId = null;
            //var response = instance.GetProjectById(projectId);
            //Assert.IsType<Project>(response);
        }

        /// <summary>
        /// Test GetProjects
        /// </summary>
        [Fact]
        public void GetProjectsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string pageAfter = null;
            //string pageBefore = null;
            //int? pageSize = null;
            //var response = instance.GetProjects(pageAfter, pageBefore, pageSize);
            //Assert.IsType<List<Project>>(response);
        }

        /// <summary>
        /// Test PostProject
        /// </summary>
        [Fact]
        public void PostProjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Project body = null;
            //var response = instance.PostProject(body);
            //Assert.IsType<Project>(response);
        }

        /// <summary>
        /// Test PutProjectById
        /// </summary>
        [Fact]
        public void PutProjectByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid projectId = null;
            //Project body = null;
            //var response = instance.PutProjectById(projectId, body);
            //Assert.IsType<Project>(response);
        }
    }
}
